# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxoWxDnxYBL2zFFxcr1kOH0ndfZW0t7L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from past.builtins import xrange
import datetime
from datetime import timedelta
from pandas import DataFrame

cgm_data = pd.read_csv('CGMData.csv')
cgm_data.head()

cgm_data_perday=cgm_data[['Index','Date','Time','Sensor Glucose (mg/dL)']]
cgm_data_perday['Sensor Glucose (mg/dL)'] = cgm_data_perday['Sensor Glucose (mg/dL)'].fillna(0)
#cgm_data1['datetime_str'] = cgm_data1['Date'].str.cat(cgm_data1['Time'].astype(str), sep=" ")
#cgm_data_perday['Date'] = pd.to_datetime(cgm_data_perday['Date'], errors='coerce').dt.date
cgm_data_perday['Date'] =  pd.to_datetime(cgm_data_perday['Date'], format='%m/%d/%Y')

list2=[]
st_date = pd.to_datetime('2017-07-25')
for j in range (0,160):
  cgmday_dataset1 = cgm_data_perday.loc[cgm_data_perday['Date'] == st_date]
  list2.append(cgmday_dataset1.values.tolist())
  st_date = st_date + datetime.timedelta(days=1)
#print(list2)
   

st_date1 = pd.to_datetime('2018-01-01')
cgmday_dataset2= cgm_data_perday.loc[cgm_data_perday['Date'] == st_date1] 
list2.append(cgmday_dataset2.values.tolist())



st_date2 = pd.to_datetime('2018-01-10')
for j in range (0,34):
  cgmday_dataset3 = cgm_data_perday.loc[cgm_data_perday['Date'] == st_date2]
  list2.append(cgmday_dataset3.values.tolist())
  st_date2 = st_date2 + datetime.timedelta(days=1)
#print(list2[194])

#list_HyperGly_finfulldays_mean=[]
#list_HyperGlyCrit_finfulldays_mean=[]
#list_range1_finfulldays_mean=[]
#list_range2_finfulldays_mean=[]
#list_HyperGlylvl1_finfulldays_mean=[]
#list_HyperGlylvl2_finfulldays_mean=[]
list_HyperGly_finfulldays=[]
list_HyperGlyCrit_finfulldays=[]
list_range1_finfulldays=[]
list_range2_finfulldays=[]
list_HyperGlylvl1_finfulldays=[]
list_HyperGlylvl2_finfulldays=[]
for row in list2:
 list_HyperGly=[]
 list_HyperGlyCrit=[]
 list_range1=[]
 list_range2=[]
 list_HyperGlylvl1=[]
 list_HyperGlylvl2=[]
 for i in row:
   if (i[3]>180.0):
     list_HyperGly.append(i[3])
   if (i[3]>250.0):
     list_HyperGlyCrit.append(i[3])
   if (i[3]>=70 and i[3]<=180.0):
     list_range1.append(i[3])
   if (i[3]>=70.0 and i[3]<=150.0):
     list_range2.append(i[3])
   if (i[3]<70.0):
     list_HyperGlylvl1.append(i[3])
   if (i[3]<54.0):
     list_HyperGlylvl2.append(i[3])     
 list_HyperGly_finfulldays.append(list_HyperGly)
 list_HyperGlyCrit_finfulldays.append(list_HyperGlyCrit)
 list_range1_finfulldays.append(list_range1)
 list_range2_finfulldays.append(list_range2)
 list_HyperGlylvl1_finfulldays.append(list_HyperGlylvl1)
 list_HyperGlylvl2_finfulldays.append(list_HyperGlylvl2)


print(list_HyperGly_finfulldays)
print(list_HyperGlyCrit_finfulldays)
print(list_range1_finfulldays)
print(list_range2_finfulldays)
print(list_HyperGlylvl1_finfulldays)
print(list_HyperGlylvl2_finfulldays)

#def sums(x):
  #return sum(x)/288

list_time=[]
for row in list2:
  templist_time=[]
  for i in row:
    templist_time.append([i[2],i[3]])
  list_time.append(templist_time)
print(list_time)

insulin_data = pd.read_csv('InsulinData.csv')
insulin_data.head()
def convert_timestamp(x):
    return datetime.datetime.strptime(x, '%m/%d/%Y %H:%M:%S')

def convert_date(x):
  int_date = x.split("/")
  date = datetime.datetime(int(int_date[2]), int(int_date[0]), int(int_date[1]))
  return date


insulin_data['Date'] = insulin_data['Date'].astype(str)
insulin_data['Date'] = insulin_data['Date'].astype(str)
insulin_data['Date'] = insulin_data['Date'].apply(convert_date)     
insulin_data['Alarm'] = insulin_data['Alarm'].fillna('')

plgm_off_timestamp = insulin_data[insulin_data['Alarm'].str.contains('AUTO MODE ACTIVE PLGM OFF')][['Date','Time']].tail(1)
plgm_off_timestamp = plgm_off_timestamp.reset_index()
plgm_off_timestamp['Date'] = plgm_off_timestamp['Date'].astype(str) 
plgm_off_timestamp['Timestamp'] = plgm_off_timestamp['Date'] +" "+ plgm_off_timestamp['Time'] 
plgm_off_timestamp = plgm_off_timestamp['Timestamp'].iloc[0]
date_time_str = plgm_off_timestamp
plgm_off_timestamp = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S')
print(plgm_off_timestamp)

#cgm_data['Date'] = cgm_data['Date'].astype(str)
#cgm_data['Date'] = cgm_data['Date'].apply(convert_date)
#cgm_data['Date'] = cgm_data['Date'].astype(str)
cgm_data['Timestamp'] = cgm_data['Date'] + ' ' + cgm_data['Time']
cgm_data['Timestamp'] = cgm_data['Timestamp'].apply(convert_timestamp)

  
trimmed_df_automode = cgm_data[cgm_data['Timestamp']>=plgm_off_timestamp] 
trimmed_df_automode

#print(trimmed_df_automode['Date'])
trimmed_df_automodefinal=trimmed_df_automode[['Index','Date','Time','Sensor Glucose (mg/dL)']]
trimmed_df_automodefinal['Sensor Glucose (mg/dL)'] = trimmed_df_automodefinal['Sensor Glucose (mg/dL)'].fillna(0)
trimmed_df_automodefinal['Date'] =  pd.to_datetime(trimmed_df_automodefinal['Date'], format='%m/%d/%Y')
print(trimmed_df_automodefinal)
list_perday_automode=[]
st_date_automode = pd.to_datetime('2017-08-09')
for j in range (0,145):
  automode_perday_dataset = trimmed_df_automodefinal.loc[trimmed_df_automodefinal['Date'] == st_date_automode]
  list_perday_automode.append(automode_perday_dataset.values.tolist())
  st_date_automode = st_date_automode + datetime.timedelta(days=1)
#print(list_perday_automode[144])

st_date_automode1 = pd.to_datetime('2018-01-01')
automode_perday_dataset1= trimmed_df_automodefinal.loc[trimmed_df_automodefinal['Date'] == st_date_automode1] 
list_perday_automode.append(automode_perday_dataset1.values.tolist())
#print(list_perday_automode[145])

st_date_automode2 = pd.to_datetime('2018-01-10')
for j in range (0,34):
  automode_perday_dataset3 = trimmed_df_automodefinal.loc[trimmed_df_automodefinal['Date'] == st_date_automode2]
  list_perday_automode.append(automode_perday_dataset3.values.tolist())
  st_date_automode2 = st_date_automode2 + datetime.timedelta(days=1)
#print(list_perday_automode[179])

list_HyperGly_automode_finfulldays=[]
list_HyperGlyCrit_automode_finfulldays=[]
list_range1_automode_finfulldays=[]
list_range2_automode_finfulldays=[]
list_HyperGlylvl1_automode_finfulldays=[]
list_HyperGlylvl2_automode_finfulldays=[]
for row in list_perday_automode:
 list_HyperGly_automode=[]
 list_HyperGlyCrit_automode=[]
 list_range1_automode=[]
 list_range2_automode=[]
 list_HyperGlylvl1_automode=[]
 list_HyperGlylvl2_automode=[]
 for i in row:
   if (i[3]>180.0):
     list_HyperGly_automode.append(i[3])
   if (i[3]>250.0):
     list_HyperGlyCrit_automode.append(i[3])
   if (i[3]>=70 and i[3]<=180.0):
     list_range1_automode.append(i[3])
   if (i[3]>=70.0 and i[3]<=150.0):
     list_range2_automode.append(i[3])
   if (i[3]<70.0):
     list_HyperGlylvl1_automode.append(i[3])
   if (i[3]<54.0):
     list_HyperGlylvl2_automode.append(i[3])       
 list_HyperGly_automode_finfulldays.append(list_HyperGly_automode)
 list_HyperGlyCrit_automode_finfulldays.append(list_HyperGlyCrit_automode)
 list_range1_automode_finfulldays.append(list_range1_automode)
 list_range2_automode_finfulldays.append(list_range2_automode)
 list_HyperGlylvl1_automode_finfulldays.append(list_HyperGlylvl1_automode)
 list_HyperGlylvl2_automode_finfulldays.append(list_HyperGlylvl2_automode)

list_HGAFF=[]
for list_HGAF in list_HyperGly_automode_finfulldays:
  list_HGAFF.append(len(list_HGAF)/288)
percentage_auto1=sum(list_HGAFF)/len(list_perday_automode)
#print(list_HGAFF)
print(percentage_auto1) 

list_HGCAFF=[]
for list_HGCAF in list_HyperGlyCrit_automode_finfulldays:
  list_HGCAFF.append(len(list_HGCAF)/288)
percentage_auto2=sum(list_HGCAFF)/len(list_perday_automode)
#print(list_HGCAFF)
print(percentage_auto2) 

list_R1AFF=[]
for list_R1AF in list_range1_automode_finfulldays:
  list_R1AFF.append(len(list_R1AF)/288)
percentage_auto3=sum(list_R1AFF)/len(list_perday_automode)
#print(list_R1AFF)
print(percentage_auto3)

list_R2AFF=[]
for list_R2AF in list_range2_automode_finfulldays:
  list_R2AFF.append(len(list_R2AF)/288)
percentage_auto4=sum(list_R2AFF)/len(list_perday_automode)
#print(list_R2AFF)
print(percentage_auto4)

list_L1AFF=[]
for list_L1AF in list_HyperGlylvl1_automode_finfulldays:
  list_L1AFF.append(len(list_L1AF)/288)
percentage_auto5=sum(list_L1AFF)/len(list_perday_automode)
#print(list_L1AFF)
print(percentage_auto5)

list_L2AFF=[]
for list_L2AF in list_HyperGlylvl2_automode_finfulldays:
  list_L2AFF.append(len(list_L2AF)/288)
percentage_auto6=sum(list_L2AFF)/len(list_perday_automode)
#print(list_L2AFF)
print(percentage_auto6)


print(list_HyperGly_automode_finfulldays)
print(list_HyperGlyCrit_automode_finfulldays) 
print(list_range1_automode_finfulldays)
print(list_range2_automode_finfulldays)
print(list_HyperGlylvl1_automode_finfulldays)
print(list_HyperGlylvl2_automode_finfulldays)

list_automode_time=[]
for row in list_perday_automode:
  templist_automode_time=[]
  for i in row:
    templist_automode_time.append([i[2],i[3]])
  list_automode_time.append(templist_automode_time)
print(list_automode_time[0])

list_HyperGly_finfulldays_automodedaytime=[]
list_HyperGlyCrit_finfulldays_automodedaytime=[]
list_range1_finfulldays_automodedaytime=[]
list_range2_finfulldays_automodedaytime=[]
list_HyperGlylvl1_finfulldays_automodedaytime=[]
list_HyperGlylvl2_finfulldays_automodedaytime=[]
for i in list_automode_time:
  time_frame_dayTime_automode=DataFrame(i, columns=['Time','Mean'])
  time_frame_dayTime_automode['Time']= pd.to_datetime(time_frame_dayTime_automode['Time']) 
  time_frame_dayTime_automode.set_index('Time', inplace=True)

  time_frame_dayTime_automode=time_frame_dayTime_automode.between_time('6:00:00','00:00:00')
  #print(time_frame_dayTime_automode)
  time_frame_dayTime_automode['Mean'] = time_frame_dayTime_automode['Mean'].fillna(0)
  list_time_frame_dayTime_automode=[]
  list_time_frame_dayTime_automode=time_frame_dayTime_automode.values.tolist()
  #print(list_time_frame_dayTime_automode)
  list_HyperGly_automodedaytime=[]
  list_HyperGlyCrit_automodedaytime=[]
  list_range1_automodedaytime=[]
  list_range2_automodedaytime=[]
  list_HyperGlylvl1_automodedaytime=[]
  list_HyperGlylvl2_automodedaytime=[]
  for rows in list_time_frame_dayTime_automode:
    # print(rows)
    for j in rows:
      if (j>180.0):
        list_HyperGly_automodedaytime.append(j)
      if (j>250.0):
        list_HyperGlyCrit_automodedaytime.append(j)
      if (j>=70.0 and j<=180.0):
        list_range1_automodedaytime.append(j)
      if (j>=70.0 and j<=150.0):
        list_range2_automodedaytime.append(j)
      if (j<70.0):
        list_HyperGlylvl1_automodedaytime.append(j)
      if (j<54.0):
        list_HyperGlylvl2_automodedaytime.append(j) 
  list_HyperGly_finfulldays_automodedaytime.append(list_HyperGly_automodedaytime)
  list_HyperGlyCrit_finfulldays_automodedaytime.append(list_HyperGlyCrit_automodedaytime)
  list_range1_finfulldays_automodedaytime.append(list_range1_automodedaytime)
  list_range2_finfulldays_automodedaytime.append(list_range2_automodedaytime)
  list_HyperGlylvl1_finfulldays_automodedaytime.append(list_HyperGlylvl1_automodedaytime)
  list_HyperGlylvl2_finfulldays_automodedaytime.append(list_HyperGlylvl2_automodedaytime)

list_HGAdayF=[]
for list_HGAday in list_HyperGly_finfulldays_automodedaytime:
  list_HGAdayF.append(len(list_HGAday)/288)
percentage_auto7=sum(list_HGAdayF)/len(list_perday_automode)
#print(list_HGAdayF)
print(percentage_auto7)

list_HGCAdayF=[]
for list_HGCAday in list_HyperGlyCrit_finfulldays_automodedaytime:
  list_HGCAdayF.append(len(list_HGCAday)/288)
percentage_auto8=sum(list_HGCAdayF)/len(list_perday_automode)
#print(list_HGCAdayF)
print(percentage_auto8)

list_R1AdayF=[]
for list_R1Aday in list_range1_finfulldays_automodedaytime:
  list_R1AdayF.append(len(list_R1Aday)/288)
percentage_auto9=sum(list_R1AdayF)/len(list_perday_automode)
#print(list_R1AdayF)
print(percentage_auto9)

list_R2AdayF=[]
for list_R2Aday in list_range2_finfulldays_automodedaytime:
  list_R2AdayF.append(len(list_R2Aday)/288)
percentage_auto10=sum(list_R2AdayF)/len(list_perday_automode)
#print(list_R2AdayF)
print(percentage_auto10)

list_L1AdayF=[]
for list_L1Aday in list_HyperGlylvl1_finfulldays_automodedaytime:
  list_L1AdayF.append(len(list_L1Aday)/288)
percentage_auto11=sum(list_L1AdayF)/len(list_perday_automode)
#print(list_L1AdayF)
print(percentage_auto11)

list_L2AdayF=[]
for list_L2Aday in list_HyperGlylvl2_finfulldays_automodedaytime:
  list_L2AdayF.append(len(list_L2Aday)/288)
percentage_auto12=sum(list_L2AdayF)/len(list_perday_automode)
#print(list_L2AdayF)
print(percentage_auto12)


print(list_HyperGly_finfulldays_automodedaytime)
print(list_HyperGlyCrit_finfulldays_automodedaytime)
print(list_range1_finfulldays_automodedaytime)
print(list_range2_finfulldays_automodedaytime)
print(list_HyperGlylvl1_finfulldays_automodedaytime)
print(list_HyperGlylvl2_finfulldays_automodedaytime)

list_HyperGly_finfulldays_automodeovernight=[]
list_HyperGlyCrit_finfulldays_automodeovernight=[]
list_range1_finfulldays_automodeovernight=[]
list_range2_finfulldays_automodeovernight=[]
list_HyperGlylvl1_finfulldays_automodeovernight=[]
list_HyperGlylvl2_finfulldays_automodeovernight=[]
for i in list_automode_time:
  time_frame_overnight_automode=DataFrame(i, columns=['Time','Mean'])
  time_frame_overnight_automode['Time']= pd.to_datetime(time_frame_overnight_automode['Time']) 
  time_frame_overnight_automode.set_index('Time', inplace=True)

  time_frame_overnight_automode=time_frame_overnight_automode.between_time('00:00:00','6:00:00')
  #print(time_frame_overnight_automode)
  time_frame_overnight_automode['Mean'] = time_frame_overnight_automode['Mean'].fillna(0)
  list_time_frame_overnight_automode=[]
  list_time_frame_overnight_automode=time_frame_overnight_automode.values.tolist()
  #print(list_time_frame_overnight_automode)
  list_HyperGly_automodeovernight=[]
  list_HyperGlyCrit_automodeovernight=[]
  list_range1_automodeovernight=[]
  list_range2_automodeovernight=[]
  list_HyperGlylvl1_automodeovernight=[]
  list_HyperGlylvl2_automodeovernight=[]
  for rows in list_time_frame_overnight_automode:
    # print(rows)
    for j in rows:
      if (j>180.0):
        list_HyperGly_automodeovernight.append(j)
      if (j>250.0):
        list_HyperGlyCrit_automodeovernight.append(j)
      if (j>=70.0 and j<=180.0):
        list_range1_automodeovernight.append(j)
      if (j>=70.0 and j<=150.0):
        list_range2_automodeovernight.append(j)
      if (j<70.0):
        list_HyperGlylvl1_automodeovernight.append(j)
      if (j<54.0):
        list_HyperGlylvl2_automodeovernight.append(j) 
  list_HyperGly_finfulldays_automodeovernight.append(list_HyperGly_automodeovernight)
  list_HyperGlyCrit_finfulldays_automodeovernight.append(list_HyperGlyCrit_automodeovernight)
  list_range1_finfulldays_automodeovernight.append(list_range1_automodeovernight)
  list_range2_finfulldays_automodeovernight.append(list_range2_automodeovernight)
  list_HyperGlylvl1_finfulldays_automodeovernight.append(list_HyperGlylvl1_automodeovernight)
  list_HyperGlylvl2_finfulldays_automodeovernight.append(list_HyperGlylvl2_automodeovernight)

list_HGAnightF=[]
for list_HGAnight in list_HyperGly_finfulldays_automodeovernight:
  list_HGAnightF.append(len(list_HGAnight)/288)
percentage_auto13=sum(list_HGAnightF)/len(list_perday_automode)
#print(list_HGAnightF)
print(percentage_auto13)

list_HGCAnightF=[]
for list_HGCAnight in list_HyperGlyCrit_finfulldays_automodeovernight:
  list_HGCAnightF.append(len(list_HGCAnight)/288)
percentage_auto14=sum(list_HGCAnightF)/len(list_perday_automode)
#print(list_HGCAnightF)
print(percentage_auto14)

list_R1AnightF=[]
for list_R1Anight in list_range1_finfulldays_automodeovernight:
  list_R1AnightF.append(len(list_R1Anight)/288)
percentage_auto15=sum(list_R1AnightF)/len(list_perday_automode)
#print(list_R1AnightF)
print(percentage_auto15)

list_R2AnightF=[]
for list_R2Anight in list_range2_finfulldays_automodeovernight:
  list_R2AnightF.append(len(list_R2Anight)/288)
percentage_auto16=sum(list_R2AnightF)/len(list_perday_automode)
#print(list_R2AnightF)
print(percentage_auto16)

list_L1AnightF=[]
for list_L1Anight in list_HyperGlylvl1_finfulldays_automodeovernight:
  list_L1AnightF.append(len(list_L1Anight)/288)
percentage_auto17=sum(list_L1AnightF)/len(list_perday_automode)
#print(list_L1AnightF)
print(percentage_auto17)

list_L2AnightF=[]
for list_L2Anight in list_HyperGlylvl2_finfulldays_automodeovernight:
  list_L2AnightF.append(len(list_L2Anight)/288)
percentage_auto18=sum(list_L2AnightF)/len(list_perday_automode)
#print(list_L2AnightF)
print(percentage_auto18)


print(list_HyperGly_finfulldays_automodeovernight)
print(list_HyperGlyCrit_finfulldays_automodeovernight)
print(list_range1_finfulldays_automodeovernight)
print(list_range2_finfulldays_automodeovernight)
print(list_HyperGlylvl1_finfulldays_automodeovernight)
print(list_HyperGlylvl2_finfulldays_automodeovernight)

insulin_data = pd.read_csv('InsulinData.csv')
insulin_data.head()
def convert_timestamp(x):
    return datetime.datetime.strptime(x, '%m/%d/%Y %H:%M:%S')

def convert_date(x):
  int_date = x.split("/")
  date = datetime.datetime(int(int_date[2]), int(int_date[0]), int(int_date[1]))
  return date



insulin_data['Date'] = insulin_data['Date'].astype(str)
insulin_data['Date'] = insulin_data['Date'].astype(str)
insulin_data['Date'] = insulin_data['Date'].apply(convert_date)     
insulin_data['Alarm'] = insulin_data['Alarm'].fillna('')
plgm_off_timestamp = insulin_data[insulin_data['Alarm'].str.contains('AUTO MODE ACTIVE PLGM OFF')][['Date','Time']].tail(1)
plgm_off_timestamp = plgm_off_timestamp.reset_index()
plgm_off_timestamp['Date'] = plgm_off_timestamp['Date'].astype(str) 
plgm_off_timestamp['Timestamp'] = plgm_off_timestamp['Date'] +" "+ plgm_off_timestamp['Time'] 
plgm_off_timestamp = plgm_off_timestamp['Timestamp'].iloc[0]
date_time_str = plgm_off_timestamp
plgm_off_timestamp = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S')
print(plgm_off_timestamp)
cgm_data['Timestamp'] = cgm_data['Date'] + ' ' + cgm_data['Time']
cgm_data['Timestamp'] = cgm_data['Timestamp'].apply(convert_timestamp)

trimmed_df_manualmode = cgm_data[cgm_data['Timestamp']<=plgm_off_timestamp] 
trimmed_df_manualmode

trimmed_df_manualmodefinal=trimmed_df_manualmode[['Index','Date','Time','Sensor Glucose (mg/dL)']]
trimmed_df_manualmodefinal['Sensor Glucose (mg/dL)'] = trimmed_df_manualmodefinal['Sensor Glucose (mg/dL)'].fillna(0)
trimmed_df_manualmodefinal['Date'] =  pd.to_datetime(trimmed_df_manualmodefinal['Date'], format='%m/%d/%Y')
print(trimmed_df_manualmodefinal)
list_perday_manualmode=[]

st_date_manualmode = pd.to_datetime('2017-07-25')
for j in range (0,16):
  manualmode_perday_dataset = trimmed_df_manualmodefinal.loc[trimmed_df_manualmodefinal['Date'] == st_date_manualmode]
  list_perday_manualmode.append(manualmode_perday_dataset.values.tolist())
  st_date_manualmode = st_date_manualmode + datetime.timedelta(days=1)
print(list_perday_manualmode)

list_HyperGly_manualmode_finfulldays=[]
list_HyperGlyCrit_manualmode_finfulldays=[]
list_range1_manualmode_finfulldays=[]
list_range2_manualmode_finfulldays=[]
list_HyperGlylvl1_manualmode_finfulldays=[]
list_HyperGlylvl2_manualmode_finfulldays=[]
for row in list_perday_manualmode:
 list_HyperGly_manualmode=[]
 list_HyperGlyCrit_manualmode=[]
 list_range1_manualmode=[]
 list_range2_manualmode=[]
 list_HyperGlylvl1_manualmode=[]
 list_HyperGlylvl2_manualmode=[]
 for i in row:
   if (i[3]>180.0):
     list_HyperGly_manualmode.append(i[3])
   if (i[3]>250.0):
     list_HyperGlyCrit_manualmode.append(i[3])
   if (i[3]>=70.0 and i[3]<=180.0):
     list_range1_manualmode.append(i[3])
   if (i[3]>=70.0 and i[3]<=150.0):
     list_range2_manualmode.append(i[3])
   if (i[3]<70.0):
     list_HyperGlylvl1_manualmode.append(i[3])
   if (i[3]<54.0):
     list_HyperGlylvl2_manualmode.append(i[3])
 list_HyperGly_manualmode_finfulldays.append(list_HyperGly_manualmode)
 list_HyperGlyCrit_manualmode_finfulldays.append(list_HyperGlyCrit_manualmode)
 list_range1_manualmode_finfulldays.append(list_range1_manualmode)
 list_range2_manualmode_finfulldays.append(list_range2_manualmode)
 list_HyperGlylvl1_manualmode_finfulldays.append(list_HyperGlylvl1_manualmode)
 list_HyperGlylvl2_manualmode_finfulldays.append(list_HyperGlylvl2_manualmode)

list_HGMFF=[]
for list_HGMF in list_HyperGly_manualmode_finfulldays:
  list_HGMFF.append(len(list_HGMF)/288)
percentage_manual1=sum(list_HGMFF)/len(list_perday_manualmode)
#print(list_HGMFF)
print(percentage_manual1) 

list_HGCMFF=[]
for list_HGCMF in list_HyperGlyCrit_manualmode_finfulldays:
  list_HGCMFF.append(len(list_HGCMF)/288)
percentage_manual2=sum(list_HGCMFF)/len(list_perday_manualmode)
#print(list_HGCMFF)
print(percentage_manual2) 

list_R1MFF=[]
for list_R1MF in list_range1_manualmode_finfulldays:
  list_R1MFF.append(len(list_R1MF)/288)
percentage_manual3=sum(list_R1MFF)/len(list_perday_manualmode)
#print(list_R1MFF)
print(percentage_manual3)

list_R2MFF=[]
for list_R2MF in list_range2_manualmode_finfulldays:
  list_R2MFF.append(len(list_R2MF)/288)
percentage_manual4=sum(list_R2MFF)/len(list_perday_manualmode)
#print(list_R2MFF)
print(percentage_manual4)

list_L1MFF=[]
for list_L1MF in list_HyperGlylvl1_manualmode_finfulldays:
  list_L1MFF.append(len(list_L1MF)/288)
percentage_manual5=sum(list_L1MFF)/len(list_perday_manualmode)
#print(list_L1MFF)
print(percentage_manual5)

list_L2MFF=[]
for list_L2MF in list_HyperGlylvl2_manualmode_finfulldays:
  list_L2MFF.append(len(list_L2MF)/288)
percentage_manual6=sum(list_L2MFF)/len(list_perday_manualmode)
#print(list_L2MFF)
print(percentage_manual6)

print(list_HyperGly_manualmode_finfulldays)
print(list_HyperGlyCrit_manualmode_finfulldays)
print(list_range1_manualmode_finfulldays)
print(list_range2_manualmode_finfulldays)
print(list_HyperGlylvl1_manualmode_finfulldays)
print(list_HyperGlylvl2_manualmode_finfulldays)

list_manualmode_time=[]
for row in list_perday_manualmode:
  templist_manualmode_time=[]
  for i in row:
    templist_manualmode_time.append([i[2],i[3]])
  list_manualmode_time.append(templist_manualmode_time)
print(list_manualmode_time[0])

list_HyperGly_finfulldays_manualmodedaytime=[]
list_HyperGlyCrit_finfulldays_manualmodedaytime=[]
list_range1_finfulldays_manualmodedaytime=[]
list_range2_finfulldays_manualmodedaytime=[]
list_HyperGlylvl1_finfulldays_manualmodedaytime=[]
list_HyperGlylvl2_finfulldays_manualmodedaytime=[]
for i in list_manualmode_time:
  time_frame_dayTime_manualmode=DataFrame(i, columns=['Time','Mean'])
  time_frame_dayTime_manualmode['Time']= pd.to_datetime(time_frame_dayTime_manualmode['Time']) 
  time_frame_dayTime_manualmode.set_index('Time', inplace=True)

  time_frame_dayTime_manualmode=time_frame_dayTime_manualmode.between_time('6:00:00','00:00:00')
  #print(time_frame_dayTime_manualmode)
  time_frame_dayTime_manualmode['Mean'] = time_frame_dayTime_manualmode['Mean'].fillna(0)
  list_time_frame_dayTime_manualmode=[]
  list_time_frame_dayTime_manualmode=time_frame_dayTime_manualmode.values.tolist()
  #print(list_time_frame_dayTime_manualmode)
  list_HyperGly_manualmodedaytime=[]
  list_HyperGlyCrit_manualmodedaytime=[]
  list_range1_manualmodedaytime=[]
  list_range2_manualmodedaytime=[]
  list_HyperGlylvl1_manualmodedaytime=[]
  list_HyperGlylvl2_manualmodedaytime=[]
  for rows in list_time_frame_dayTime_manualmode:
    # print(rows)
    for j in rows:
      if (j>180.0):
        list_HyperGly_manualmodedaytime.append(j)
      if (j>250.0):
        list_HyperGlyCrit_manualmodedaytime.append(j)
      if (j>=70.0 and j<=180.0):
        list_range1_manualmodedaytime.append(j)
      if (j>=70.0 and j<=150.0):
        list_range2_manualmodedaytime.append(j)
      if (j<70.0):
        list_HyperGlylvl1_manualmodedaytime.append(j)
      if (j<54.0):
        list_HyperGlylvl2_manualmodedaytime.append(j) 
  list_HyperGly_finfulldays_manualmodedaytime.append(list_HyperGly_manualmodedaytime)
  list_HyperGlyCrit_finfulldays_manualmodedaytime.append(list_HyperGlyCrit_manualmodedaytime)
  list_range1_finfulldays_manualmodedaytime.append(list_range1_manualmodedaytime)
  list_range2_finfulldays_manualmodedaytime.append(list_range2_manualmodedaytime)
  list_HyperGlylvl1_finfulldays_manualmodedaytime.append(list_HyperGlylvl1_manualmodedaytime)
  list_HyperGlylvl2_finfulldays_manualmodedaytime.append(list_HyperGlylvl2_manualmodedaytime)

list_HGMdayF=[]
for list_HGMday in list_HyperGly_finfulldays_manualmodedaytime:
  list_HGMdayF.append(len(list_HGMday)/288)
percentage_manual7=sum(list_HGMdayF)/len(list_perday_manualmode)
#print(list_HGMdayF)
print(percentage_manual7) 

list_HGCMdayF=[]
for list_HGCMday in list_HyperGlyCrit_finfulldays_manualmodedaytime:
  list_HGCMdayF.append(len(list_HGCMday)/288)
percentage_manual8=sum(list_HGCMdayF)/len(list_perday_manualmode)
#print(list_HGCMdayF)
print(percentage_manual8) 

list_R1MdayF=[]
for list_R1Mday in list_range1_finfulldays_manualmodedaytime:
  list_R1MdayF.append(len(list_R1Mday)/288)
percentage_manual9=sum(list_R1MdayF)/len(list_perday_manualmode)
#print(list_R1MdayF)
print(percentage_manual9)

list_R2MdayF=[]
for list_R2Mday in list_range2_finfulldays_manualmodedaytime:
  list_R2MdayF.append(len(list_R2Mday)/288)
percentage_manual10=sum(list_R2MdayF)/len(list_perday_manualmode)
#print(list_R2MdayF)
print(percentage_manual10)

list_L1MdayF=[]
for list_L1Mday in list_HyperGlylvl1_finfulldays_manualmodedaytime:
  list_L1MdayF.append(len(list_L1Mday)/288)
percentage_manual11=sum(list_L1MdayF)/len(list_perday_manualmode)
#print(list_L1MdayF)
print(percentage_manual11)

list_L2MdayF=[]
for list_L2Mday in list_HyperGlylvl2_finfulldays_manualmodedaytime:
  list_L2MdayF.append(len(list_L2Mday)/288)
percentage_manual12=sum(list_L2MdayF)/len(list_perday_manualmode)
#print(list_L2MdayF)
print(percentage_manual12)  


print(list_HyperGly_finfulldays_manualmodedaytime)
print(list_HyperGlyCrit_finfulldays_manualmodedaytime)
print(list_range1_finfulldays_manualmodedaytime)
print(list_range2_finfulldays_manualmodedaytime)
print(list_HyperGlylvl1_finfulldays_manualmodedaytime)
print(list_HyperGlylvl2_finfulldays_manualmodedaytime)

list_HyperGly_finfulldays_manualmodeovernight=[]
list_HyperGlyCrit_finfulldays_manualmodeovernight=[]
list_range1_finfulldays_manualmodeovernight=[]
list_range2_finfulldays_manualmodeovernight=[]
list_HyperGlylvl1_finfulldays_manualmodeovernight=[]
list_HyperGlylvl2_finfulldays_manualmodeovernight=[]
for i in list_manualmode_time:
  time_frame_overnight_manualmode=DataFrame(i, columns=['Time','Mean'])
  time_frame_overnight_manualmode['Time']= pd.to_datetime(time_frame_overnight_manualmode['Time']) 
  time_frame_overnight_manualmode.set_index('Time', inplace=True)

  time_frame_overnight_manualmode=time_frame_overnight_manualmode.between_time('00:00:00','6:00:00')
  #print(time_frame_overnight_manualmode)
  time_frame_overnight_manualmode['Mean'] = time_frame_overnight_manualmode['Mean'].fillna(0)
  list_time_frame_overnight_manualmode=[]
  list_time_frame_overnight_manualmode=time_frame_overnight_manualmode.values.tolist()
  #print(list_time_frame_overnight_manualmode)
  list_HyperGly_manualmodeovernight=[]
  list_HyperGlyCrit_manualmodeovernight=[]
  list_range1_manualmodeovernight=[]
  list_range2_manualmodeovernight=[]
  list_HyperGlylvl1_manualmodeovernight=[]
  list_HyperGlylvl2_manualmodeovernight=[]
  for rows in list_time_frame_overnight_manualmode:
    # print(rows)
    for j in rows:
      if (j>180.0):
        list_HyperGly_manualmodeovernight.append(j)
      if (j>250.0):
        list_HyperGlyCrit_manualmodeovernight.append(j)
      if (j>=70.0 and j<=180.0):
        list_range1_manualmodeovernight.append(j)
      if (j>=70.0 and j<=150.0):
        list_range2_manualmodeovernight.append(j)
      if (j<70.0):
        list_HyperGlylvl1_manualmodeovernight.append(j)
      if (j<54.0):
        list_HyperGlylvl2_manualmodeovernight.append(j) 
  list_HyperGly_finfulldays_manualmodeovernight.append(list_HyperGly_manualmodeovernight)
  list_HyperGlyCrit_finfulldays_manualmodeovernight.append(list_HyperGlyCrit_manualmodeovernight)
  list_range1_finfulldays_manualmodeovernight.append(list_range1_manualmodeovernight)
  list_range2_finfulldays_manualmodeovernight.append(list_range2_manualmodeovernight)
  list_HyperGlylvl1_finfulldays_manualmodeovernight.append(list_HyperGlylvl1_manualmodeovernight)
  list_HyperGlylvl2_finfulldays_manualmodeovernight.append(list_HyperGlylvl2_manualmodeovernight)

list_HGMnightF=[]
for list_HGMnight in list_HyperGly_finfulldays_manualmodeovernight:
  list_HGMnightF.append(len(list_HGMnight)/288)
percentage_manual13=sum(list_HGMnightF)/len(list_perday_manualmode)
#print(list_HGMnightF)
print(percentage_manual13) 

list_HGCMnightF=[]
for list_HGCMnight in list_HyperGlyCrit_finfulldays_manualmodeovernight:
  list_HGCMnightF.append(len(list_HGCMnight)/288)
percentage_manual14=sum(list_HGCMnightF)/len(list_perday_manualmode)
#print(list_HGCMnightF)
print(percentage_manual14) 

list_R1MnightF=[]
for list_R1Mnight in list_range1_finfulldays_manualmodeovernight:
  list_R1MnightF.append(len(list_R1Mnight)/288)
percentage_manual15=sum(list_R1MnightF)/len(list_perday_manualmode)
#print(list_R1MnightF)
print(percentage_manual15)

list_R2MnightF=[]
for list_R2Mnight in list_range2_finfulldays_manualmodeovernight:
  list_R2MnightF.append(len(list_R2Mnight)/288)
percentage_manual16=sum(list_R2MnightF)/len(list_perday_manualmode)
#print(list_R2MnightF)
print(percentage_manual16)

list_L1MnightF=[]
for list_L1Mnight in list_HyperGlylvl1_finfulldays_manualmodeovernight:
  list_L1MnightF.append(len(list_L1Mnight)/288)
percentage_manual17=sum(list_L1MnightF)/len(list_perday_manualmode)
#print(list_L1MnightF)
print(percentage_manual17)

list_L2MnightF=[]
for list_L2Mnight in list_HyperGlylvl2_finfulldays_manualmodeovernight:
  list_L2MnightF.append(len(list_L2Mnight)/288)
percentage_manual18=sum(list_L2MnightF)/len(list_perday_manualmode)
#print(list_L2MnightF)
print(percentage_manual18) 


print(list_HyperGly_finfulldays_manualmodeovernight)
print(list_HyperGlyCrit_finfulldays_manualmodeovernight)
print(list_range1_finfulldays_manualmodeovernight)
print(list_range2_finfulldays_manualmodeovernight)
print(list_HyperGlylvl1_finfulldays_manualmodeovernight)
print(list_HyperGlylvl2_finfulldays_manualmodeovernight)

result_df = pd.DataFrame(columns=['','Percentage time in hyperglycemia (CGM > 180 mg/dL)', 'percentage of time in hyperglycemia critical (CGM > 250 mg/dL)', 'percentage time in range (CGM >= 70 mg/dL and CGM <= 180 mg/dL)','percentage time in range secondary (CGM >= 70 mg/dL and CGM <= 150 mg/dL)','percentage time in hypoglycemia level 1 (CGM < 70 mg/dL)','percentage time in hypoglycemia level 2 (CGM < 54 mg/dL)','Percentage time in hyperglycemia (CGM > 180 mg/dL)(daytime)','percentage of time in hyperglycemia critical (CGM > 250 mg/dL)(daytime)','percentage time in range (CGM >= 70 mg/dL and CGM <= 180 mg/dL)(daytime)','percentage time in range secondary (CGM >= 70 mg/dL and CGM <= 150 mg/dL)(daytime)','percentage time in hypoglycemia level 1 (CGM < 70 mg/dL)(daytime)','percentage time in hypoglycemia level 2 (CGM < 54 mg/dL)(daytime)','Percentage time in hyperglycemia (CGM > 180 mg/dL)(Overnight)','percentage of time in hyperglycemia critical (CGM > 250 mg/dL)(Overnight)','percentage time in range (CGM >= 70 mg/dL and CGM <= 180 mg/dL)(Overnight)','percentage time in range secondary (CGM >= 70 mg/dL and CGM <= 150 mg/dL)(Overnight)','percentage time in hypoglycemia level 1 (CGM < 70 mg/dL)(Overnight)','percentage time in hypoglycemia level 2 (CGM < 54 mg/dL)(Overnight)'])
index=['Manual Mode','Auto Mode']
result_df.loc[0]=['Manual Mode',percentage_manual1,percentage_manual2,percentage_manual3,percentage_manual4,percentage_manual5,percentage_manual6,percentage_manual7,percentage_manual8,percentage_manual9,percentage_manual10,percentage_manual11,percentage_manual12,percentage_manual13,percentage_manual14,percentage_manual15,percentage_manual16,percentage_manual17,percentage_manual18]
result_df.loc[1]=['Auto Mode',percentage_auto1,percentage_auto2,percentage_auto3,percentage_auto4,percentage_auto5,percentage_auto6,percentage_auto7,percentage_auto8,percentage_auto9,percentage_auto10,percentage_auto11,percentage_auto12,percentage_auto13,percentage_auto14,percentage_auto15,percentage_auto16,percentage_auto17,percentage_auto18]
result_df
result_df.to_csv('Makhijani_Results.csv',index = False)
print(result_df.head)

